### ISSUE TITLE
Modification warning

### ISSUE THREAD

**Issue by CesarHerreraG** [ChristianPauly/jotit#2]
When a writen message is modified there should appear an advertising. And confirm the modification if you want.

**Comment by krille-chan** [comment]
Thank you for your suggestion. But the idea of the app is that it saves automatically in background all the time and the user has nothing to do. There are missing features like save, roll-back etc. because of making it more minimalistic. The use-case is only to make quick notes, not to write long articles.

**Comment by CesarHerreraG** [comment]
Rollback may be thr

**Comment by CesarHerreraG** [comment]
Rollback may be the solution.

**Comment by CesarHerreraG** [comment]
If you use this app as a diary, you don't want the records to change for a mistake.

**Comment by krille-chan** [comment]
A simple rollback button should be very easy to implement. I will think about :)

**Comment by CesarHerreraG** [comment]
Thanks.

**Comment by CesarHerreraG** [comment]
Another way is make uneditable each message.

**Comment by krille-chan** [comment]
Undo button is implemented =)

**Comment by CesarHerreraG** [comment]
Thanks.
